- name: configure frontend
  become: yes
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete default config
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html dir
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download ans extract fromtend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy backend conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: reatsrt nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      
